#!/bin/sh
#
# Small wrapper that takes the secret files from the folder
#
###############################################################################
echo "Command line: $0 $@"

crypt4gh-wrap /secret/testcineca.sk /secret/ega_key.c4gh.pub $(cat /secret/sftpkeypassword) $@
